// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarR88AX8pTiWPUZ6sE990AEylDO1NlLA',
    appId: '1:1091955552892:web:8388035d459453ca334ff9',
    messagingSenderId: '1091955552892',
    projectId: 'health-care-176ad',
    authDomain: 'health-care-176ad.firebaseapp.com',
    databaseURL: 'https://health-care-176ad-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-176ad.appspot.com',
    measurementId: 'G-VPJBHQKJCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fo6Y_5-bG9PsTXRXrLbjyie364XjkwQ',
    appId: '1:1091955552892:android:f687ed83978110bd334ff9',
    messagingSenderId: '1091955552892',
    projectId: 'health-care-176ad',
    databaseURL: 'https://health-care-176ad-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-176ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuX2LkDiX6tMI1btUneFNlMZSeJulmaKk',
    appId: '1:1091955552892:ios:d161bd90689131c7334ff9',
    messagingSenderId: '1091955552892',
    projectId: 'health-care-176ad',
    databaseURL: 'https://health-care-176ad-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-176ad.appspot.com',
    iosClientId: '1091955552892-ll6icjum9m7lqb6k9boo97jqefkd0utp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuX2LkDiX6tMI1btUneFNlMZSeJulmaKk',
    appId: '1:1091955552892:ios:d161bd90689131c7334ff9',
    messagingSenderId: '1091955552892',
    projectId: 'health-care-176ad',
    databaseURL: 'https://health-care-176ad-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-176ad.appspot.com',
    iosClientId: '1091955552892-ll6icjum9m7lqb6k9boo97jqefkd0utp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTwo',
  );
}
